### ISSUE TITLE
Cryptic error when invalid Access Token provided

### ISSUE THREAD

**Issue by erikgranlund** [JasonSanford/mapmyfitness-python#20]
If you provide an incorrect access token and then attempt to perform a search in workouts or routes you get this error:

```
Traceback (most recent call last):
  File "test_mmf.py", line 6, in <module>
    mmf.workout.search(user=9118466)
  File "/Users/egranlund/git/fitbit_api/mapmyfitness/api/mixins.py", line 23, in search
    for obj in api_resp['_embedded'][self.embedded_name]:
KeyError: '_embedded'
```

When I had it print out the **api_resp** variable, it contained:

```
{u'oauth1_error': u'Malformed authorization header', u'oauth2_error': u'AccessToken not found.', u'oauth1_error_code': u'OAUTH1:UNKNOWN', u'oauth2_error_code': u'OAUTH2:ACCESSTOKEN_NOT_FOUND'}
```

Here is the code I used:

```
from mapmyfitness import MapMyFitness
from config import *

mmf = MapMyFitness(api_key=MMF_CLIENT_KEY, access_token=MMF_SECRET_KEY)

mmf.workout.search(user=9118466)
```

Turns out I was providing the secret key for my application, rather than the OAUTH token. When I switched the variables out the error was resolved. Newbie error, but I was scratching my head for a couple of minutes :)

**Comment by JasonSanford** [comment]
Thanks for the feedback.

Can't test it now, but I'd be curious what HTTP status code you're getting for that `api_resp`.

I'll try and work up a failing test case and some code for a better error message.

**Comment by JasonSanford** [comment]
This was returning an HTTP 401, an error that should be caught. This should be fixed now. Thanks again for the heads up.

**Comment by erikgranlund** [comment]
Great - thanks for the quick fix :+1:
