### ISSUE TITLE
Add a paginator to be used for all object types

### ISSUE THREAD

**Issue by bnekolny** [JasonSanford/mapmyfitness-python#9]
Here is a sample paginator use-case:
https://github.com/splunk/splunk-sdk-python/blob/70931cd7bc56a891f48c6f77469957b233aa0557/tests/test_collection.py#L213

**Comment by JasonSanford** [comment]
I got pagination working. It works like this: https://gist.github.com/JasonSanford/ddbe06832e5d17061b8a
